
project_id = "thcmyhermklehzjdmhio"

[functions.perplexity-api]
verify_jwt = false

[functions.fetch-mortgage-rates]
verify_jwt = true
schedule = "@daily"

[functions.get-mortgage-rates]
verify_jwt = false

