// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thcmyhermklehzjdmhio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoY215aGVybWtsZWh6amRtaGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTE2MzgsImV4cCI6MjA1OTcyNzYzOH0.RGqrpB5m9wyoq2TFRlmfMONUOsa-PBEc4bMtYPO9-jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);